export const GET_SHIPPER_ORDER_REQUEST = 'GET_SHIPPER_ORDER_REQUEST';
export const GET_SHIPPER_ORDER_SUCCESS = 'GET_SHIPPER_ORDER_SUCCESS';
export const GET_SHIPPER_ORDER_FAILURE = 'GET_SHIPPER_ORDER_FAILURE';

export const GET_HISTORY_SHIPPER_ORDER_REQUEST = 'GET_HISTORY_SHIPPER_ORDER_REQUEST';
export const GET_HISTORY_SHIPPER_ORDER_SUCCESS = 'GET_HISTORY_SHIPPER_ORDER_SUCCESS';
export const GET_HISTORY_SHIPPER_ORDER_FAILURE = 'GET_HISTORY_SHIPPER_ORDER_FAILURE';

export const UPDATE_SHIPPER_ORDER_REQUEST = 'UPDATE_SHIPPER_ORDER_REQUEST';
export const UPDATE_SHIPPER_ORDER_SUCCESS = 'UPDATE_SHIPPER_ORDER_SUCCESS';
export const UPDATE_SHIPPER_ORDER_FAILURE = 'UPDATE_SHIPPER_ORDER_FAILURE';

export const UPDATE_COMPLETED_ORDER_REQUEST = 'UPDATE_COMPLETED_ORDER_REQUEST';
export const UPDATE_COMPLETED_ORDER_SUCCESS = 'UPDATE_COMPLETED_ORDER_SUCCESS';
export const UPDATE_COMPLETED_ORDER_FAILURE = 'UPDATE_COMPLETED_ORDER_FAILURE';